### ISSUE TITLE
Cache the sieve

### ISSUE THREAD

**Issue by dsernst** [TJkrusinski/isprime#1]
I was using this library to test primality of all of the numbers up to 1,000,000 for this problem: https://projecteuler.net/problem=35

Unfortunately I couldn't get my program to finish in a reasonable amount of time without modifying this library.

Instead of generating a new sieve each time, I had it only do it a single time for my max number. This allowed the program to finish after about 10 seconds. Here's the modification I made:

``` js
var sieve = (function buildSieve(num) {
  num += 2;

  var sieve = new Array(num)
    .join(',').split(',') // get values for map to work
    .map(function () { return true; });

  var i, j;
  for (i = 2; i <= num; i++) {
    if (sieve[i]) {
      for (j = i * i; j < num; j += i) {
        sieve[j] = false;
      }
    }
  }
  return sieve;
}(max));

function isPrime(num) {
  if (num === 1) {return false; }
  return sieve[num];
}
```

Would you be open to a PR to allow for this usage?

**Comment by dsernst** [comment]
If anyone else wants this functionality, I implemented it here: https://github.com/dsernst/quick-is-prime

**Comment by TJkrusinski** [comment]
@dsernst since the function is pure you could memoize the function with any memoizing library, I'd rather keep the functionality simple.

**Comment by dsernst** [comment]
Would that work in this case, where we're testing millions of different numbers? Since the input would be different each time, wouldn't the memoization see a cache miss and re-run the function?

**Comment by TJkrusinski** [comment]
Oh duh, I totall misread this. You are right with the sieve needing to be cached and the function not memoized. I saw you created your own library but if you'd like to send the PR suggested above I'd merge.
